### 넘파이 ndarray 개요

In [2]:
import numpy as np

In [6]:
array1 = np.array([[1,2,3]])
print("array1 type:", type(array1))
print("array1 shape:", array1.shape)
print("array1 dimension:", array1.ndim)

array1 type: <class 'numpy.ndarray'>
array1 shape: (1, 3)
array1 dimension: 2


### ndarray의 데이터 타입

In [10]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,'test'])
array3 = np.array([1,2,3.0])

In [11]:
#타입 확인
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)

[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [12]:
#타입 변경
array1_float = array1.astype('float64') # int -> float
print(array1_float, array1_float.dtype)
array3_float = array3.astype('int32') # float -> int
print(array3_float, array3_float.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### ndarray를 편리하게 생성하기 

In [14]:
#arange
sequence_array = np.arange(10)
print(sequence_array, sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)


In [17]:
#zeros
zero_array = np.zeros((3,2)) # default: float64
print(zero_array, zero_array.dtype, zero_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]] float64 (3, 2)


In [18]:
#ones
one_array = np.ones((3,2),dtype='int32') # int32 지정 
print(one_array, one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]] int32 (3, 2)


### ndarray의 차원과 크기 변경

In [19]:
array1 = np.arange(10)

In [21]:
array2 = array1.reshape(2,5)
print('array1:\n', array1)
print('array2:\n', array2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
array3 = array1.reshape(-1,5)
print('array3 shape:', array3.shape)

array3 shape: (2, 5)


### 넘파이의 ndarray의 데이터 세트 선택하기 

In [27]:
array1 = np.arange(1,10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [28]:
#단일값추출
value = array1[2] # 3번째 index 
print('value:', value)

value: 3


In [29]:
#슬라이싱
array2 = array1[0:3] # 3번째 index까지 
print(array2)

[1 2 3]


In [32]:
#팬시인덱싱
array3 = array1.reshape(3,3) # 1차원 -> 2차원
array4 = array3[[0,1],2] # (0,2), (1,2)
array5 = array3[[0,1],0:2] # ((0,0), (0,1)), ((1,0),(1,1))
print('array3[[0,1],2]=>', array4.tolist())
print('array3[[0,1],0:2]=>', array5.tolist())

array3[[0,1],2]=> [3, 6]
array3[[0,1],0:2]=> [[1, 2], [4, 5]]


In [34]:
#불린인덱싱
array6 = array1[array1>5]
print('array1>5 불린 인덱싱 결과:', array6)

array1>5 불린 인덱싱 결과: [6 7 8 9]


### 행렬의 정렬

In [42]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

원본 행렬: [3 1 9 5]


In [46]:
#sort
#np.sort()로 정렬: 원 행렬 유지
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬: 원 행렬 자체 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

np.sort() 호출 후 반환된 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [48]:
#argsort
org_array = np.array([3,1,9,5])
sort_indicies = np.argsort(org_array)
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indicies)

행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


### 선형대수 연산

In [38]:
A = np.array([[1,2,3],[4,5,6]]) # (2,3)
B = np.array([[7,8],[9,10],[11,12]]) # (3,2)
print('A:\n', A)
print('B:\n', B)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [39]:
#행렬내적
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [41]:
#전치행렬
transpose_mat1 = np.transpose(A)
transpose_mat2 = np.transpose(B)
print('A의 전치 행렬:\n', transpose_mat1)
print('B의 전치 행렬:\n', transpose_mat2)

A의 전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
B의 전치 행렬:
 [[ 7  9 11]
 [ 8 10 12]]
